### ISSUE TITLE
Mission Documents SOCC and SOTG views

### ISSUE THREAD

**Issue by ghost** [mahaloatchaboy/CrisisResponse#12]
Remove "group by Organization"; 
add organization; add organization column ahead of name; 
order by organization, then name

**Comment by chanm003** [comment]
Organization on the Sotg.aspx?  Won't that be redundant? Task groups such as "SOTG 20" don't have a "SOTG 20 - J2", do they?

**Comment by chanm003** [comment]
For SOCC and SOAC, show Organization column before name
