### ISSUE TITLE
Documents webpart: Click link to view all documents of that type

### ISSUE THREAD

**Issue by mcleanra** [mahaloatchaboy/CrisisResponse#22]
As a user of the JSOAC-E exercise page, I want to be able to click on the name of a document type in the 'Documents' webpart and be taken to a page that shows me a list of all documents of this type that are from my organization so that I can more quickly find the documents I am looking for.

Users original complaint is that it's hard to find the document he is looking for; he recommended this as a potential solution.

Stakeholder: JSOAC-E
@btroop202

**Comment by chanm003** [comment]
See #21 

With item limit changed, clicking on "Images" document type will expand the entire grouping so they can see all images without paging
